# Generated by Django 2.2.7 on 2019-11-18 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='nomTontine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name="Nom Complet de l'adhérent: ")),
                ('dateCreation', models.DateTimeField(verbose_name='Date de Fin ')),
                ('cotisations', models.CharField(blank=True, choices=[(10, '10 jours'), (20, '20 jours'), (30, '30 jours'), (40, '40 jours')], max_length=15, null=True, verbose_name='Cotisation par ')),
                ('creerPar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ajoutar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cotisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dateAjoute', models.DateTimeField(auto_now_add=True, verbose_name='Date de Début ')),
                ('nomAderent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontines.nomTontine')),
            ],
        ),
        migrations.CreateModel(
            name='adherents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name="Nom Complet de l'adhérent: ")),
                ('adresse', models.CharField(max_length=100, verbose_name="Adresse Complet de l'adhérent: ")),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name="email de l'adhérent: ")),
                ('telephone', models.CharField(max_length=13, verbose_name="téléphone de l'adhérent: ")),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création ')),
                ('statut', models.BooleanField(default=False)),
                ('creerPar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
