# Generated by Django 2.2.7 on 2019-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomtontine',
            name='dateCreation',
        ),
        migrations.AddField(
            model_name='nomtontine',
            name='dateDébut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nomtontine',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
