# Generated by Django 2.2.7 on 2019-11-18 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0002_auto_20191118_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomtontine',
            name='dateDébut',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='nomtontine',
            name='dateFin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='nomtontine',
            name='nom',
            field=models.CharField(max_length=120, verbose_name='Nom de la Tontine: '),
        ),
    ]
