# Generated by Django 2.2.7 on 2019-11-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0003_auto_20191118_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='nomAderent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nom_adherant', to='tontines.adherents'),
        ),
    ]
