# Generated by Django 2.2.7 on 2019-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0004_auto_20191118_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisation',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
