# Generated by Django 2.2.7 on 2019-11-19 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontines', '0005_auto_20191118_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherents',
            name='dateCreation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de Création '),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='dateAjoute',
            field=models.DateField(auto_now_add=True, verbose_name='Date de Début '),
        ),
        migrations.AlterField(
            model_name='nomtontine',
            name='dateDébut',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='nomtontine',
            name='dateFin',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
